language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t koitoror/my-react-hooks-docker-app -f Dockerfile.dev .

script:
  - docker run -e CI=true koitoror/my-react-hooks-docker-app npm run test

after_success:
  - docker build -t koitoror/my-react-hooks-docker-app .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push koitoror/my-react-hooks-docker-app
